title: Kevin's Resume
author: Kevin Solis
email: ksolis1513@gmail.com
description: I am a responsable, dedicated, well-organized and self-motivated person.I like to learn new things to constantly increase my abilities and also work very hard to always provide my very best on anything I do.

# social links
github_username:  ksolis15

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
